# Site Settings
text_skin: default
highlight_theme: tomorrow
url     : https://blog.duongludien.com
baseurl : # does not include hostname
title   : Giáo dục - Triết học - Khoa học máy tính
description: >
    Giáo dục - Triết học - Khoa học máy tính


# Language and Timezone
lang: en
timezone: Asia/Ho_Chi_Minh


# Author and Social
author:
  type      : person
  name      : Dương Lữ Điện
  url       : https://blog.duongludien.com
  avatar    : # path or url of avatar image
  bio       : A human being
  linkedin  : duongludien
  github    : duongludien


# GitHub Repository (if the site is hosted by GitHub)
repository: duongludien/duongludien.github.io
repository_tree: master


# Paths
paths:
  root    : "/"
  home    : "/"
  archive : "/archive.html"
  rss     : "/feed.xml"


# Post
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-SA-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: "h1,h2,h3"


# Markdown Enhancements
## Mathjax
mathjax: true
mathjax_autoNumber: true

## Mermaid
mermaid: true

## Chart
chart: true


# Paginate
paginate: 8
paginate_path: /page:num # don't change this unless for special need


# Sources
sources: # bootcdn (default), unpkg


# Comments
comments:
  provider: disqus

  ## Disqus
  disqus:
    shortname: blog-duongludien-com


## => Pageview
##############################
pageview:
  provider: false # false (default), "leancloud", "custom"

  ## Leancloud
  leancloud:
    app_id    : # LeanCloud App id
    app_key   : # LeanCloud App key
    app_class : # LeanCloud App class


## => Analytics
##############################
analytics:
  provider: false # false (default), "google", "custom"

  ## Google Analytics
  google:
    tracking_id : # Google Analytics id for the site
    anonymize_ip: false # Anonymize IP tracking for Analytics


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      pageview: true


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
