apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
  annotations:
    kubernetes.io/ingress.class: "public" 
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k" 
{{ if .Values.ingress.enable_tls }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls_clusterIssuer }}
    kubernetes.io/tls-acme: "true"
{{ end }}
spec:
{{ if .Values.ingress.enable_tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.blog_hostname }}
    secretName: tls-secrets
{{ end }}
  rules:
  - host: {{ .Values.ingress.blog_hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80