name: Build and Deploy a Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 setup
        uses: actions/checkout@v2

        # include the lines below if you are using jekyll-last-modified-at
        # or if you would otherwise need to fetch the full commit history
        # however this may be very slow for large repositories!
        # with:
        # fetch-depth: '0'
      - name: 💎 setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - run: bundle config set --local path 'vendor/bundle'
      - run: bundle install --jobs=8 --retry=3 --gemfile=./Gemfile
#      - run: ls -al

      - name: 🔨 install dependencies & build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
          jekyll_src: ./
          gem_src: ./
          
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          # Path of the directory containing the static assets.
          path: ./_site
          # Duration after which artifact will expire in days.
          retention-days: 1 # optional, default is 1

  deploy:
    # Add a dependency to the build job
    needs: setup

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.2
        with:
          # Should this action only emit build telemetry instead of deploying the build artifact?
          emit_telemetry: false # optional, default is false
          # The status of the previous build.
          # conclusion: # optional
          # GitHub token
          token: ${{ secrets.GITHUB_TOKEN }} # default is ${{ github.token }}
          # Time in milliseconds after which to timeout and cancel the deployment (default: 10 minutes)
          timeout: 600000
          # Maximum number of status report errors before cancelling a deployment (default: 10)
          error_count: 10
          # Time in milliseconds between two deployment status report (default: 5 seconds)
          reporting_interval: 5000
          # Name of the artifact to deploy
          artifact_name: github-pages
          # Is this attempting to deploy a pull request as a GitHub Pages preview site? (NOTE: This feature is only in alpha currently and is not available to the public!)
          preview: false
