on: 
  push
  #pull_request:
  #  branches:
  #    - my-blog
  #  types: [closed]
jobs:
  # `build` is a user-defined name for this job
  publish-blog-content:
    # Set the base environment to run the Action on
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: mkdir test && cd test && > foo.txt && chmod 777 ../test/
      - name: Step 5 - FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          LOCAL_DIR: test
          REMOTE_DIR: blog
          METHOD: sftp
          PORT: 22
          ARGS: --delete